#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
从 exp2/analyze_race_sensitive_MLPs.py 生成的 results_mlp.pkl 中，
使用肘部点原则选择种族敏感的 MLP 层，并将结果保存为 JSON/Pickle。

输出：
- selected_mlp_layers_elbow.json: [{"layer": int}, ...]
- results_mlp_elbow.pkl: 包含 layer_kl_scores, elbow_score, elbow_idx, rank_array, selected_layers
"""

import argparse
import json
import os
import pickle
from typing import List, Dict, Any

import numpy as np

# 导入上层目录工具函数
import sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'src'))

from util import compute_elbow_point, compute_rank_array  # type: ignore  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Select race-sensitive MLP layers using elbow-point from results_mlp.pkl",
    )
    parser.add_argument(
        "--results_path",
        type=str,
        required=True,
        help="Path to results_mlp.pkl generated by analyze_race_sensitive_MLPs.py",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="race_sensitive_mlp_selected",
        help="Directory to save selected_mlp_layers_elbow.json and results_mlp_elbow.pkl",
    )
    args = parser.parse_args()

    if not os.path.exists(args.results_path):
        raise FileNotFoundError(f"results_mlp.pkl not found: {args.results_path}")

    os.makedirs(args.output_dir, exist_ok=True)

    with open(args.results_path, "rb") as f:
        data: Dict[str, Any] = pickle.load(f)

    if "layer_kl_scores" not in data:
        raise KeyError("results_mlp.pkl must contain 'layer_kl_scores'")

    layer_kl_scores = np.asarray(data["layer_kl_scores"], dtype=np.float64)
    num_layers = layer_kl_scores.shape[0]

    finite_mask = np.isfinite(layer_kl_scores)
    finite_scores = layer_kl_scores[finite_mask]
    if finite_scores.size == 0:
        raise ValueError("No finite KL scores in layer_kl_scores.")

    sorted_scores = np.sort(finite_scores)[::-1]
    elbow_idx, elbow_score = compute_elbow_point(sorted_scores)

    rank_array = compute_rank_array(layer_kl_scores.reshape(num_layers, 1))

    selected_layers: List[Dict[str, int]] = []
    for l in range(num_layers):
        score = float(layer_kl_scores[l])
        if not np.isfinite(score):
            continue
        if score >= float(elbow_score):
            selected_layers.append({"layer": int(l)})

    json_path = os.path.join(args.output_dir, "selected_mlp_layers_elbow.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(selected_layers, f, indent=2)

    out_pkl = {
        "layer_kl_scores": layer_kl_scores,
        "num_layers": int(num_layers),
        "elbow_idx": int(elbow_idx),
        "elbow_score": float(elbow_score),
        "rank_array": rank_array,
        "selected_layers": selected_layers,
    }
    pkl_path = os.path.join(args.output_dir, "results_mlp_elbow.pkl")
    with open(pkl_path, "wb") as f:
        pickle.dump(out_pkl, f)

    print("=" * 60)
    print("MLP Elbow Selection Summary")
    print("=" * 60)
    print(f"Loaded KL scores for {num_layers} layers from: {args.results_path}")
    print(f"Elbow index (on sorted scores): {int(elbow_idx)}")
    print(f"Elbow score (threshold): {float(elbow_score):.6f}")
    print(f"Number of selected layers: {len(selected_layers)}")
    print(f"Output directory: {args.output_dir}")
    print(f"  - JSON: {json_path}")
    print(f"  - PKL:  {pkl_path}")
    print("=" * 60)


if __name__ == "__main__":
    main()
